"""
Generate a ready-to-build Packer HCL template for an AL2023 replacement AMI,
derived from a user-supplied package list and (optionally) scanned results.
"""
from __future__ import annotations
import argparse
from pathlib import Path
from . import util, remap


PACKER_TEMPLATE = '''# Generated by al2023-gate · Amazon Linux 2 → AL2023 migration kit
# https://github.com/ntoledo319/Rupture
#
# Build: packer init . && packer build al2023.pkr.hcl
# Prereqs: packer >= 1.9, AWS credentials with EC2/IAM permissions.

packer {{
  required_plugins {{
    amazon = {{
      source  = "github.com/hashicorp/amazon"
      version = ">= 1.2.0"
    }}
  }}
}}

variable "region"              {{ type = string  default = "{region}" }}
variable "instance_type"       {{ type = string  default = "{instance_type}" }}
variable "ami_name"            {{ type = string  default = "{ami_name}" }}
variable "architecture"        {{ type = string  default = "{arch}" }}
variable "source_ami_owner"    {{ type = string  default = "137112412989" }}   # Amazon
variable "source_ami_filter"   {{ type = string  default = "al2023-ami-2023*" }}
variable "subnet_id"           {{ type = string  default = "" }}
variable "kms_key_id"          {{ type = string  default = "" }}

source "amazon-ebs" "al2023" {{
  region        = var.region
  instance_type = var.instance_type
  ami_name      = "${{var.ami_name}}-${{formatdate("YYYY-MM-DD-hhmm", timestamp())}}"
  ssh_username  = "ec2-user"
  source_ami_filter {{
    filters = {{
      name                = var.source_ami_filter
      virtualization-type = "hvm"
      architecture        = var.architecture
      root-device-type    = "ebs"
    }}
    most_recent = true
    owners      = [var.source_ami_owner]
  }}
  dynamic "launch_block_device_mappings" {{
    for_each = var.kms_key_id == "" ? [] : [1]
    content {{
      device_name           = "/dev/xvda"
      volume_size           = 20
      volume_type           = "gp3"
      encrypted             = true
      kms_key_id            = var.kms_key_id
      delete_on_termination = true
    }}
  }}
  dynamic "subnet_filter" {{
    for_each = var.subnet_id == "" ? [1] : []
    content {{
      filters = {{ "default-for-az" = "true" }}
      most_free = true
      random    = false
    }}
  }}
  subnet_id = var.subnet_id == "" ? null : var.subnet_id
  tags = {{
    Name          = var.ami_name
    OS            = "Amazon Linux 2023"
    BuiltBy       = "al2023-gate"
    SourceCommand = "al2023-gate packer"
  }}
}}

build {{
  sources = ["source.amazon-ebs.al2023"]

  # 1. Ensure dnf is up to date
  provisioner "shell" {{
    inline = [
      "set -euo pipefail",
      "sudo dnf -y upgrade --refresh",
    ]
  }}

  # 2. Install packages (AL2023 equivalents)
  provisioner "shell" {{
    inline = [
      "set -euo pipefail",
      "sudo dnf -y install \\\\",
{pkg_install_lines}
    ]
  }}

{custom_blocks}

  # 3. Disable SELinux-breaking legacy iptables paths (optional, opt-in)
  # provisioner "shell" {{
  #   inline = ["sudo dnf -y install iptables-legacy", "sudo alternatives --set iptables /usr/sbin/iptables-legacy"]
  # }}

  # 4. Lock down root, harden SSH, and enable chrony (AL2023 default time sync)
  provisioner "shell" {{
    inline = [
      "sudo systemctl enable --now chronyd",
      "sudo sed -i 's/^#PermitRootLogin.*/PermitRootLogin no/' /etc/ssh/sshd_config",
      "sudo systemctl restart sshd",
    ]
  }}

  # 5. Clean image
  provisioner "shell" {{
    inline = [
      "sudo dnf clean all",
      "sudo rm -rf /var/cache/dnf /tmp/* /var/tmp/*",
      "sudo rm -f /home/ec2-user/.ssh/authorized_keys /root/.ssh/authorized_keys",
      "sudo cloud-init clean --logs",
    ]
  }}
}}
'''

MIGRATION_REPORT_TEMPLATE = '''# AL2 → AL2023 package migration report

Generated by `al2023-gate packer` on {today}.

## Summary

| Category | Count |
|---|---|
{summary_rows}

## Actions required

{action_sections}

## Primary source
https://aws.amazon.com/amazon-linux-2/faqs/
'''


def _render_pkg_install(pkgs):
    safe = []
    for p in pkgs:
        if p and p != "-":
            safe.append(f'"      {p} \\\\"')
    joined = ",\n".join(safe)
    # Strip trailing backslash on last line
    lines = joined.split("\n")
    if lines:
        lines[-1] = lines[-1].replace(' \\\\"', '"')
    return "\n".join(lines)


def run(args: argparse.Namespace) -> int:
    util.hdr(f"Packer template generator · {args.out}")
    src_packages = []
    if args.packages:
        src_packages = [s for s in (p.strip() for p in Path(args.packages).read_text().splitlines())
                        if s and not s.startswith("#")]
    elif args.from_list:
        src_packages = [p.strip() for p in args.from_list.split(",") if p.strip()]
    else:
        src_packages = ["nginx", "git", "htop", "curl"]  # sensible default

    util.info(f"Input packages: {len(src_packages)}")
    entries = remap.remap_package_list(src_packages)
    buckets = remap.categorize(entries)

    install_names = []
    action_items = []
    for e in entries:
        if e.category == "removed":
            action_items.append(f"- **{e.al2_name}** — REMOVED in AL2023. {e.note}")
            continue
        if e.category in ("replaced_by", "extras_to_dnf", "renamed"):
            action_items.append(f"- `{e.al2_name}` → `{e.al2023_name}` ({e.category}). {e.note}")
        if e.al2023_name:
            install_names.append(e.al2023_name)

    # de-dup while preserving order
    seen = set()
    install_names = [x for x in install_names if not (x in seen or seen.add(x))]

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)
    hcl_path = out_dir / "al2023.pkr.hcl"
    report_path = out_dir / "migration-report.md"

    hcl = PACKER_TEMPLATE.format(
        region=args.region,
        instance_type=args.instance_type,
        ami_name=args.name,
        arch=args.arch,
        pkg_install_lines=_render_pkg_install(install_names),
        custom_blocks="",
    )
    hcl_path.write_text(hcl)

    from datetime import date
    summary_rows = "\n".join(
        f"| {cat} | {len(items)} |"
        for cat, items in sorted(buckets.items())
    )
    report_path.write_text(MIGRATION_REPORT_TEMPLATE.format(
        today=date.today().isoformat(),
        summary_rows=summary_rows or "| none | 0 |",
        action_sections="\n".join(action_items) if action_items else "None — all packages have clean equivalents.",
    ))

    util.ok(f"wrote {hcl_path}")
    util.ok(f"wrote {report_path}")
    util.info(f"Next: `cd {out_dir} && packer init . && packer build al2023.pkr.hcl`")
    return 0