"""
Audit PDF generation using WeasyPrint.
Creates hash-anchored, deterministic reports.
"""

import hashlib
import json
from datetime import datetime
from pathlib import Path
from typing import Optional

from jinja2 import Template


PDF_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Rupture Audit Report</title>
    <style>
        @page { margin: 2cm; }
        body { font-family: system-ui, -apple-system, sans-serif; line-height: 1.6; }
        h1 { color: #1f2937; border-bottom: 2px solid #2563eb; padding-bottom: 0.5rem; }
        h2 { color: #374151; margin-top: 2rem; }
        .header { background: #f9fafb; padding: 1rem; border-radius: 8px; margin-bottom: 2rem; }
        .meta { color: #6b7280; font-size: 0.875rem; }
        .severity { display: inline-block; padding: 0.25rem 0.5rem; border-radius: 4px; font-weight: 600; }
        .severity-critical { background: #fef2f2; color: #dc2626; }
        .severity-high { background: #fff7ed; color: #ea580c; }
        .severity-medium { background: #fefce8; color: #ca8a04; }
        .severity-low { background: #f0fdf4; color: #16a34a; }
        table { width: 100%; border-collapse: collapse; margin: 1rem 0; }
        th, td { padding: 0.75rem; text-align: left; border-bottom: 1px solid #e5e7eb; }
        th { background: #f9fafb; font-weight: 600; }
        .verification { background: #eff6ff; padding: 1rem; border-radius: 8px; margin-top: 2rem; }
        code { background: #f3f4f6; padding: 0.125rem 0.25rem; border-radius: 4px; font-family: monospace; }
        .cover { page-break-after: always; }
        .deterministic { text-align: center; color: #059669; font-weight: 600; margin-top: 2rem; }
    </style>
</head>
<body>
    <div class="cover">
        <h1>Rupture Audit Report</h1>
        <p class="deterministic">Deterministic ✅</p>
        
        <div class="header">
            <p><strong>Generated:</strong> {{ generated_at }}</p>
            <p><strong>Rule Pack Version:</strong> {{ rule_pack_version }}</p>
            <p><strong>Input Hash (SHA-256):</strong> <code>{{ input_hash }}</code></p>
        </div>
        
        <h2>Executive Summary</h2>
        <p>This report identifies {{ total_findings }} deprecated runtime patterns across your infrastructure.</p>
        
        <table>
            <tr>
                <th>Category</th>
                <th>Count</th>
                <th>Risk Score</th>
            </tr>
            {% for category in categories %}
            <tr>
                <td>{{ category.name }}</td>
                <td>{{ category.count }}</td>
                <td>{{ category.risk_score }}</td>
            </tr>
            {% endfor %}
        </table>
        
        {% if cost_estimate %}
        <h2>Cost of Not Fixing</h2>
        <p>Estimated downtime cost: <strong>${{ cost_estimate }}</strong></p>
        <p class="meta">Based on historical outage data for this deprecation type.</p>
        {% endif %}
    </div>
    
    <h2>Findings (Sorted by Severity × Blast Radius)</h2>
    
    {% for finding in findings %}
    <div class="finding">
        <h3>
            <span class="severity severity-{{ finding.severity_class }}">
                {{ finding.severity }} × {{ finding.blast_radius }}
            </span>
            {{ finding.title }}
        </h3>
        <p>{{ finding.description }}</p>
        <p class="meta">Location: {{ finding.location }}</p>
        {% if finding.remediation %}
        <p><strong>Remediation:</strong> {{ finding.remediation }}</p>
        {% endif %}
    </div>
    {% endfor %}
    
    <h2>Roll-Forward Roadmap</h2>
    <p>The next deprecations affecting your stack:</p>
    <ol>
        {% for deprecation in upcoming_deprecations %}
        <li><strong>{{ deprecation.name }}</strong> — {{ deprecation.date }}</li>
        {% endfor %}
    </ol>
    
    <div class="verification">
        <h3>Verification</h3>
        <p>Verify this report at:</p>
        <code>{{ verify_url }}</code>
        <p class="meta">This report is cryptographically tied to your input files. Any modification invalidates the hash.</p>
    </div>
    
    <footer style="margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #e5e7eb; color: #6b7280; font-size: 0.875rem;">
        <p>Generated by Rupture | https://ntoledo319.github.io/Rupture</p>
        <p>This report is valid for 30 days from generation.</p>
    </footer>
</body>
</html>
"""


def generate_audit_pdf(
    upload_url: Optional[str],
    email: str,
    deadline: Optional[str] = None,
    output_path: Optional[str] = None
) -> str:
    """Generate an audit PDF report."""
    from weasyprint import HTML
    
    # In a real implementation:
    # 1. Download files from upload_url
    # 2. Run kit analysis
    # 3. Calculate input hash
    # 4. Generate findings
    
    # For now, create sample data
    input_content = b"sample input for hashing"
    input_hash = hashlib.sha256(input_content).hexdigest()
    
    findings = [
        {
            "severity": 9,
            "severity_class": "critical",
            "blast_radius": 0.9,
            "title": "Lambda Node.js 20 runtime deprecated",
            "description": "12 Lambda functions using deprecated Node.js 20 runtime",
            "location": "us-east-1, us-west-2",
            "remediation": "Update to Node.js 22 using lambda-lifeline",
        },
        {
            "severity": 6,
            "severity_class": "medium",
            "blast_radius": 0.5,
            "title": "aws-sdk v2 usage detected",
            "description": "3 functions using aws-sdk v2 which is deprecated in Node.js 22",
            "location": "src/handlers/*.js",
            "remediation": "Migrate to aws-sdk v3",
        },
    ]
    
    # Sort by severity * blast_radius
    findings.sort(key=lambda f: f["severity"] * f["blast_radius"], reverse=True)
    
    template = Template(PDF_TEMPLATE)
    html_content = template.render(
        generated_at=datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"),
        rule_pack_version="2024.04.29",
        input_hash=input_hash,
        total_findings=len(findings),
        findings=findings,
        categories=[
            {"name": "Runtime Deprecations", "count": 12, "risk_score": 86},
            {"name": "Dependency Issues", "count": 3, "risk_score": 42},
        ],
        cost_estimate="12,500" if deadline else None,
        upcoming_deprecations=[
            {"name": "Amazon Linux 2 EOL", "date": "2026-06-30"},
            {"name": "Lambda Python 3.9 EOL", "date": "2026-10-31"},
        ],
        verify_url=f"https://ntoledo319.github.io/Rupture/verify/{input_hash}",
    )
    
    # Generate PDF
    if output_path is None:
        output_path = f"/tmp/audit_{input_hash[:8]}.pdf"
    
    HTML(string=html_content).write_pdf(output_path)
    
    # Embed metadata
    # WeasyPrint allows setting PDF metadata including custom properties
    # The hash is also visible in the PDF content itself
    
    return output_path
