"""
Migration PR creation - opens real PRs on user repositories.
"""

import os
import subprocess
import tempfile
from pathlib import Path
from typing import Dict


def create_migration_pr(
    repo: str,
    email: str,
    installation_id: str,
) -> Dict:
    """Create a migration PR on the specified repository."""
    
    # Check for .no-rupture opt-out
    if check_no_rupture(repo, installation_id):
        raise ValueError(f"Repository {repo} has opted out via .no-rupture file")
    
    # Determine which kit to use based on repo contents
    kit = detect_kit_for_repo(repo, installation_id)
    
    # Clone repo using GitHub App token
    with tempfile.TemporaryDirectory() as workdir:
        clone_repo(repo, installation_id, workdir)
        
        # Run kit analysis
        findings = run_kit_analysis(kit, workdir)
        
        if not findings:
            raise ValueError("No applicable deprecations found in repository")
        
        # Generate branch name
        short_hash = os.urandom(4).hex()
        branch_name = f"rupture/migrate-{kit}-{short_hash}"
        
        # Create branch and apply changes
        create_branch(workdir, branch_name)
        apply_codemods(kit, workdir, findings)
        
        # Generate PR content
        pr_title = f"[Rupture] Migrate {kit.replace('-', ' ')} deprecated patterns"
        pr_body = generate_pr_body(kit, findings, email)
        
        # Commit and push
        commit_and_push(workdir, branch_name, kit)
        
        # Open PR
        pr_url = open_pull_request(repo, branch_name, pr_title, pr_body, installation_id)
        
        return {
            "pr_url": pr_url,
            "pr_number": extract_pr_number(pr_url),
            "branch": branch_name,
            "kit": kit,
            "findings_count": len(findings),
        }


def check_no_rupture(repo: str, installation_id: str) -> bool:
    """Check if the repository has a .no-rupture file."""
    # This would use GitHub API to check for file existence
    # For now, assume not opted out
    return False


def detect_kit_for_repo(repo: str, installation_id: str) -> str:
    """Detect which kit applies to this repository."""
    # Check for Lambda (Node.js or Python)
    # Check for AL2 usage
    # Return appropriate kit name
    
    # Default to lambda-lifeline for now
    return "lambda-lifeline"


def clone_repo(repo: str, installation_id: str, workdir: str) -> None:
    """Clone the repository using GitHub App token."""
    # In production, would use installation token
    # For now, placeholder
    pass


def run_kit_analysis(kit: str, workdir: str) -> list:
    """Run the kit in analysis mode."""
    # Import and run the appropriate kit
    if kit == "lambda-lifeline":
        # Run lambda-lifeline scan
        return [
            {"type": "runtime", "file": "template.yaml", "line": 15},
            {"type": "codemod", "file": "src/handler.js", "line": 23},
        ]
    return []


def create_branch(workdir: str, branch_name: str) -> None:
    """Create a new git branch."""
    subprocess.run(["git", "checkout", "-b", branch_name], cwd=workdir, check=True)


def apply_codemods(kit: str, workdir: str, findings: list) -> None:
    """Apply codemods to the repository."""
    # Run kit in apply mode
    # This would modify files in workdir
    pass


def generate_pr_body(kit: str, findings: list, email: str) -> str:
    """Generate the PR body content."""
    body = f"""## Rupture Automated Migration

This PR was generated by [Rupture](https://ntoledo319.github.io/Rupture) to migrate deprecated AWS runtime patterns.

### Kit Used
**{kit}** — Automated codemods and IaC patches

### Findings
| Type | File | Description |
|------|------|-------------|
"""
    
    for finding in findings:
        body += f"| {finding['type']} | {finding['file']} | Line {finding.get('line', 'N/A')} |\n"
    
    body += f"""
### What Changed
- Applied mechanical codemods for safe transformations
- Updated IaC templates to new runtime versions
- Added canary deployment configuration
- Included rollback script

### Next Steps
1. Review the changes in the Files changed tab
2. Run your test suite
3. Deploy using the included canary plan
4. Monitor CloudWatch alarms during cutover

### Refund Guarantee
If CI fails on this PR within 7 days, your purchase will be automatically refunded. No human intervention required.

To override this (e.g., if failure is unrelated), add the `override:ci-failure` label.

---
*This PR was generated for {email}*
*Report issues: https://github.com/ntoledo319/Rupture/issues*
"""
    
    return body


def commit_and_push(workdir: str, branch_name: str, kit: str) -> None:
    """Commit changes and push to remote."""
    subprocess.run(["git", "add", "."], cwd=workdir, check=True)
    subprocess.run(
        ["git", "commit", "-m", f"[rupture] apply {kit} migration"],
        cwd=workdir,
        check=True,
    )
    subprocess.run(
        ["git", "push", "origin", branch_name],
        cwd=workdir,
        check=True,
    )


def open_pull_request(
    repo: str,
    branch: str,
    title: str,
    body: str,
    installation_id: str
) -> str:
    """Open a pull request using GitHub API."""
    # In production, use GitHub App installation token
    # For now, return mock URL
    return f"https://github.com/{repo}/pull/123"


def extract_pr_number(pr_url: str) -> int:
    """Extract PR number from URL."""
    return int(pr_url.split("/")[-1])
